"use client";

import { Copy, Download, FileText, Plus, Search, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { Assessment } from "@/types/assessment";
import { learningAreaLabel } from "@/data/curriculum";
import { exportAssessmentWord } from "@/services/assessment-export";

export function AssessmentLibrary({ assessments, onCreate, onOpen, onDuplicate, onDelete }: { assessments: Assessment[]; onCreate: () => void; onOpen: (assessment: Assessment) => void; onDuplicate: (assessment: Assessment) => void; onDelete: (id: string) => void }) {
  const [query, setQuery] = useState("");
  const filtered = useMemo(() => assessments.filter((item) => `${item.title} ${item.subject} ${item.competencies.map((entry) => entry.text).join(" ")}`.toLowerCase().includes(query.toLowerCase())), [assessments, query]);
  return <div className="assessment-page"><div className="page-heading"><div><span className="eyebrow">Assessment library</span><h1>Saved assessments</h1><p>Open, edit, duplicate, export, or delete complete assessment packages.</p></div><button className="primary-btn" onClick={onCreate}><Plus />Create assessment</button></div><section className="library-card"><div className="library-head"><div><h2>All assessments</h2><span>{filtered.length} saved</span></div><div className="filters"><label><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search assessments" /></label></div></div>{filtered.length ? <div className="assessment-library-list"><div className="assessment-library-row header"><span>Assessment</span><span>Curriculum</span><span>Items</span><span>Updated</span><span>Actions</span></div>{filtered.map((assessment) => <div className="assessment-library-row" key={assessment.id} onClick={() => onOpen(assessment)}><span><b>{assessment.title}</b><small>{assessment.testType} · {assessment.competencies.length} competencies</small></span><span>{learningAreaLabel(assessment.grade, assessment.subject)} · Term {assessment.term}</span><span>{assessment.totalItems}</span><span>{new Date(assessment.updatedAt).toLocaleDateString()}</span><span className="row-actions"><button title="Open or edit" onClick={(event) => { event.stopPropagation(); onOpen(assessment); }}><FileText /></button><button title="Duplicate" onClick={(event) => { event.stopPropagation(); onDuplicate(assessment); }}><Copy /></button><button title="Export test to Word" onClick={(event) => { event.stopPropagation(); exportAssessmentWord(assessment, "test"); }}><Download /></button><button title="Delete" onClick={(event) => { event.stopPropagation(); if (confirm("Delete this saved assessment from this device?")) onDelete(assessment.id); }}><Trash2 /></button></span></div>)}</div> : <div className="empty-state"><FileText /><h3>No saved assessments yet</h3><p>Create a TOS, summative test, and answer key in one workflow.</p><button className="primary-btn" onClick={onCreate}><Plus />Create assessment</button></div>}</section></div>;
}
