"use client";

import { useMemo, useState } from "react";
import { Clock3, Copy, FileCheck2, FilePlus2, Files, MoreHorizontal, Search, Trash2 } from "lucide-react";
import { LessonPlan } from "@/types/lesson-plan";
import { areaAbbreviation, termLabel } from "@/data/curriculum";

export function Dashboard({ plans, stats, compact, onCreate, onOpen, onDelete }: { plans: LessonPlan[]; stats: {total:number;drafts:number;completed:number}; compact?: boolean; onCreate:()=>void; onOpen:(plan:LessonPlan)=>void; onDelete:(id:string)=>void }) {
  const [query,setQuery]=useState(""); const [status,setStatus]=useState("All");
  const filtered=useMemo(()=>plans.filter(p=>(status==="All"||p.status===status)&&`${p.title} ${p.area} ${p.section}`.toLowerCase().includes(query.toLowerCase())),[plans,query,status]);
  return <div className="dashboard-page"><div className="page-heading"><div><span className="eyebrow">Your workspace</span><h1>{compact?"Lesson plan library":"Good day, Teacher Leny."}</h1><p>{compact?"Search, reopen, duplicate, or continue any saved lesson plan.":"Continue a draft or begin a new Monday–Thursday plan."}</p></div><button className="primary-btn" onClick={onCreate}><FilePlus2/>Create lesson plan</button></div>
    {!compact&&<div className="stat-grid"><Stat icon={<Files/>} label="All plans" value={stats.total}/><Stat icon={<Clock3/>} label="Drafts" value={stats.drafts}/><Stat icon={<FileCheck2/>} label="Completed" value={stats.completed}/></div>}
    <section className="library-card"><div className="library-head"><div><h2>{compact?"All lesson plans":"Recent lesson plans"}</h2><span>{filtered.length} {filtered.length===1?"plan":"plans"}</span></div><div className="filters"><label><Search/><input placeholder="Search plans" value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option>All</option><option>Draft</option><option>Completed</option></select></div></div>
      {filtered.length?<div className="plan-table"><div className="plan-row header"><span>Lesson</span><span>Curriculum</span><span>Status</span><span>Last modified</span><span></span></div>{filtered.map(p=><div className="plan-row" key={p.id} onClick={()=>onOpen(p)} role="button" tabIndex={0}><span><b>{p.title}</b><small>Grade {p.grade} · {p.section}</small></span><span>{areaAbbreviation[p.area]} · {termLabel(p.term)} · Week {p.week}</span><span><i className={p.status.toLowerCase()}/>{p.status}</span><span>{new Date(p.updatedAt).toLocaleDateString()}</span><span className="row-actions"><button title="Duplicate" onClick={e=>{e.stopPropagation(); const copy={...p,id:`${p.id}-copy-${Date.now()}`,title:`${p.title} (Copy)`,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}; onOpen(copy);}}><Copy/></button><button title="Delete" onClick={e=>{e.stopPropagation(); if(confirm("Delete this lesson plan from this device?"))onDelete(p.id)}}><Trash2/></button><MoreHorizontal/></span></div>)}</div>:<div className="empty-state"><FilePlus2/><h3>No lesson plans here yet</h3><p>Your saved drafts and completed plans will appear here.</p><button className="primary-btn" onClick={onCreate}>Create your first plan</button></div>}
    </section></div>;
}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="stat-card"><span>{icon}</span><div><b>{value}</b><small>{label}</small></div></div>}
