import { LessonPlan } from "@/types/lesson-plan";
import { learningAreaLabel } from "@/data/curriculum";

export function LessonPreview({ plan }: { plan: LessonPlan }) {
  const cell = (getter: (index:number)=>React.ReactNode) => Array.from({length:4},(_,i)=><td key={i}>{i<plan.sessions.length?getter(i):""}</td>);
  return <article className="paper" id="printable-plan"><header><p>Republic of the Philippines</p><b>DEPARTMENT OF EDUCATION</b><p>{plan.profile.region}</p><p>{plan.profile.division}</p><p>{plan.profile.district}</p><strong>{plan.profile.school}</strong><p>{plan.profile.location}</p><h2>LESSON PLAN</h2></header><table><thead><tr><th></th>{["MONDAY","TUESDAY","WEDNESDAY","THURSDAY"].map(d=><th key={d}>{d}</th>)}</tr></thead><tbody>
    <Row label="Name of Lesson">{cell(()=>plan.title)}</Row><Row label="Learning Area/s">{cell(()=>learningAreaLabel(plan.grade, plan.area))}</Row><Row label="Designed by Teacher/s">{cell(()=>plan.profile.teacherName)}</Row><Row label="Designed for which Grade Level and Section">{cell(()=>`GRADE ${plan.grade} - ${plan.section}`)}</Row><Row label="No. of Sessions">{cell(i=>`SESSION ${i+1}`)}</Row><Row label="References">{cell(()=>plan.references)}</Row><Row label="Declaration of AI use">{cell(()=>plan.aiDeclaration)}</Row>
    <SectionRow title="INTENTIONS"/><Row label="Learning Competency">{cell(()=>plan.competencyText)}</Row><Row label="Learning Objectives">{cell(i=><ul>{plan.sessions[i].objectives.map(o=><li key={o}>{o}</li>)}</ul>)}</Row><Row label="Learner Context">{cell(i=>plan.sessions[i].learnerContext)}</Row>
    <SectionRow title="LEARNING EXPERIENCE"/><Row label="Pre-Lesson">{cell(i=>plan.sessions[i].preLesson)}</Row><Row label="Flow">{cell(i=><div className="flow-cell"><b>I DO</b>{plan.sessions[i].flow.iDo}<b>WE DO</b>{plan.sessions[i].flow.weDo}<b>YOU DO</b>{plan.sessions[i].flow.youDo}<b>SYNTHESIS</b>{plan.sessions[i].flow.synthesis}</div>)}</Row><Row label="Learning Resources">{cell(i=>plan.sessions[i].resources.join(", "))}</Row><Row label="Opportunities for integration">{cell(i=>plan.sessions[i].integration)}</Row>
    <SectionRow title="ASSESSMENT"/><Row label="Formative Assessment">{cell(i=>plan.sessions[i].assessment)}</Row><SectionRow title="WAYS FORWARD"/><Row label="Extended learning opportunities">{cell(i=>plan.sessions[i].extendedLearning)}</Row><Row label="Reflections">{cell(i=>plan.sessions[i].reflection)}</Row>
  </tbody></table><footer><div><b>Prepared by:</b><strong>{plan.profile.teacherName}</strong><span>{plan.profile.position}</span></div><div><b>Checked and Reviewed by:</b><strong>{plan.profile.schoolHead}</strong><span>{plan.profile.schoolHeadPosition}</span></div></footer></article>;
}
function Row({label,children}: {label:string;children:React.ReactNode}) { return <tr><th>{label}</th>{children}</tr>; }
function SectionRow({title}: {title:string}) { return <tr className="section-row"><th>{title}</th><td colSpan={4}>Meaningful, inclusive, and purposeful learning experiences.</td></tr>; }
