import { LessonPlan } from "@/types/lesson-plan";
import { learningAreaLabel } from "@/data/curriculum";
import { ASSESSMENT_DESCRIPTION, LEARNING_EXPERIENCE_DESCRIPTION } from "@/data/lesson-plan-copy";

export function LessonPreview({ plan }: { plan: LessonPlan }) {
  const cell = (getter: (index:number)=>React.ReactNode) => Array.from({length:4},(_,i)=><td key={i}>{i<plan.sessions.length?getter(i):""}</td>);
  return <article className="paper" id="printable-plan"><header><img className="document-logo" src="/deped-seal.png" alt="Department of Education seal"/><p>Republic of the Philippines</p><b>DEPARTMENT OF EDUCATION</b><p>{plan.profile.region}</p><p>{plan.profile.division}</p><p>{plan.profile.district}</p><strong>{plan.profile.school}</strong><p>{plan.profile.location}</p><h2>LESSON PLAN</h2></header><table><thead><tr><th></th>{["MONDAY","TUESDAY","WEDNESDAY","THURSDAY"].map(d=><th key={d}>{d}</th>)}</tr></thead><tbody>
    <MergedRow label="Name of Lesson">{plan.title}</MergedRow><MergedRow label="Learning Area/s">{learningAreaLabel(plan.grade, plan.area)}</MergedRow><MergedRow label="Designed by Teacher/s">{plan.profile.teacherName}</MergedRow><MergedRow label="Designed for which Grade Level and Section">{`GRADE ${plan.grade} - ${plan.section}`}</MergedRow><Row label="No. of Sessions">{cell(i=>`SESSION ${i+1}`)}</Row><MergedRow label="References">{plan.references}</MergedRow><MergedRow label="Declaration of AI use">{plan.aiDeclaration}</MergedRow>
    <SectionRow title="INTENTIONS"/><Row label="Learning Competency">{cell(()=>plan.competencyText)}</Row><Row label="Learning Objectives">{cell(i=><ul>{plan.sessions[i].objectives.map(o=><li key={o}>{o}</li>)}</ul>)}</Row><Row label="Learner Context">{cell(i=>plan.sessions[i].learnerContext)}</Row>
    <SectionRow title="LEARNING EXPERIENCE" description={LEARNING_EXPERIENCE_DESCRIPTION}/><Row label="Pre-Lesson">{cell(i=>plan.sessions[i].preLesson)}</Row><Row label="Flow">{cell(i=><div className="flow-cell"><b>I DO</b>{plan.sessions[i].flow.iDo}<b>WE DO</b>{plan.sessions[i].flow.weDo}<b>YOU DO</b>{plan.sessions[i].flow.youDo}<b>SYNTHESIS</b>{plan.sessions[i].flow.synthesis}</div>)}</Row><Row label="Learning Resources">{cell(i=>plan.sessions[i].resources.join(", "))}</Row><Row label="Opportunities for integration">{cell(i=>plan.sessions[i].integration)}</Row>
    <SectionRow title="ASSESSMENT" description={ASSESSMENT_DESCRIPTION}/><Row label="Formative Assessment">{cell(i=>plan.sessions[i].assessment)}</Row><SectionRow title="WAYS FORWARD"/><Row label="Extended learning opportunities">{cell(i=>plan.sessions[i].extendedLearning)}</Row><Row label="Reflections">{cell(i=>plan.sessions[i].reflection)}</Row>
  </tbody></table><footer><div className="signature-block"><span className="signature-label">Prepared by:</span><strong>{plan.profile.teacherName}</strong><span>{plan.profile.position}</span></div><div className="signature-block"><span className="signature-label">Checked and Reviewed by:</span><strong>{plan.profile.schoolHead}</strong><span>{plan.profile.schoolHeadPosition}</span></div></footer></article>;
}
function Row({label,children}: {label:string;children:React.ReactNode}) { return <tr><th>{label}</th>{children}</tr>; }
function MergedRow({label,children}: {label:string;children:React.ReactNode}) { return <tr><th>{label}</th><td colSpan={4}>{children}</td></tr>; }
function SectionRow({title,description="Meaningful, inclusive, and purposeful learning experiences."}: {title:string;description?:string}) { return <tr className="section-row"><th>{title}</th><td colSpan={4}>{description}</td></tr>; }
